env_vars:
- name: google
  env_var: GOOGLE_DISCOVERY
  
- name: github
  env_var: GITHUB_DISCOVERY

- name: k8s
  env_var: K8S_DISCOVERY

- name: concourse
  env_var: CONCOURSE_DISCOVERY

- name: circleci
  env_var: CIRCLECI_DISCOVERY